name: CI Pipeline

on: [push, pull_request]  # Ejecuta el workflow en cada push o pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Usa un sistema Ubuntu en GitHub Actions
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

